const ROLES = {
  ADMIN: "admin",
  USER: "user",
};

const PERMISSIONS = {
  // Users
  MANAGE_USERS: "manage_users",
  READ_USERS: "read_users",
  READ_MYSELF: "read_myself",
  UPDATE_MYSELF: "update_myself",

  // Categories
  MANAGE_CATEGORIES: "manage_categories",
  READ_CATEGORIES: "read_categories",

  // Orders
  READ_ALL_ORDERS: "read_all_orders",
  READ_OWN_ORDERS: "read_own_orders",
  MANAGE_ALL_ORDERS: "manage_all_orders",
  MANAGE_OWN_ORDERS: "manage_own_orders",

  // Order Items
  READ_ALL_ORDER_ITEMS: "read_all_order_items",
  READ_OWN_ORDER_ITEMS: "read_own_order_items",
  MANAGE_ALL_ORDER_ITEMS: "manage_all_order_items",
  MANAGE_OWN_ORDER_ITEMS: "manage_own_order_items",

  // Products
  READ_ALL_PRODUCTS: "read_all_products",
  MANAGE_PRODUCTS: "manage_products",
};

const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.READ_USERS,
    PERMISSIONS.READ_MYSELF,
    PERMISSIONS.UPDATE_MYSELF,

    PERMISSIONS.MANAGE_CATEGORIES,
    PERMISSIONS.READ_CATEGORIES,

    PERMISSIONS.READ_ALL_ORDERS,
    PERMISSIONS.READ_OWN_ORDERS,
    PERMISSIONS.MANAGE_ALL_ORDERS,
    PERMISSIONS.MANAGE_OWN_ORDERS,

    PERMISSIONS.READ_ALL_ORDER_ITEMS,
    PERMISSIONS.READ_OWN_ORDER_ITEMS,
    PERMISSIONS.MANAGE_ALL_ORDER_ITEMS,
    PERMISSIONS.MANAGE_OWN_ORDER_ITEMS,

    PERMISSIONS.READ_ALL_PRODUCTS,
    PERMISSIONS.MANAGE_PRODUCTS,
  ],
  [ROLES.USER]: [
    PERMISSIONS.READ_MYSELF,
    PERMISSIONS.UPDATE_MYSELF,

    PERMISSIONS.READ_CATEGORIES,

    PERMISSIONS.READ_OWN_ORDERS,
    PERMISSIONS.MANAGE_OWN_ORDERS,

    PERMISSIONS.READ_OWN_ORDER_ITEMS,
    PERMISSIONS.MANAGE_OWN_ORDER_ITEMS,

  ],
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
};
